universe=docker

docker_image = registry.cvib.ucla.edu/blchau:3dnet
docker_pull_policy = always

executable = /radraid/blchau/3D-UNet/scripts/kidney/iso-run_1-128_patch_stride-no_filter/train_model.sh
arguments = /radraid/blchau/3D-UNet/scripts/kidney/iso-run_1-128_patch_stride-no_filter/train_config.yaml
transfer_input_files = /radraid/blchau/3D-UNet/scripts/kidney/iso-run_1-128_patch_stride-no_filter/train_config.yaml

should_transfer_files = YES

when_to_transfer_output = ON_EXIT

output = /radraid/blchau/3D-UNet/scripts/kidney/iso-run_1-128_patch_stride-no_filter/train_logs/$(cluster).$(process).out
error = /radraid/blchau/3D-UNet/scripts/kidney/iso-run_1-128_patch_stride-no_filter/train_logs/$(cluster).$(process).err
log = /radraid/blchau/3D-UNet/scripts/kidney/iso-run_1-128_patch_stride-no_filter/train_logs/$(cluster).$(process).log

request_cpus = 1
request_gpus = 2
request_memory = 100GB
request_disk = 5MB
gpus_minimum_memory = 10GB
requirements = (OpSys == "LINUX" && Arch == "X86_64")

############################################################
############################################################
### REMEMBER TO CHANGE CHECKPOINT DIRECTORY IN YAML FILE ###
############################################################
############################################################

queue
