universe=docker

docker_image = registry.cvib.ucla.edu/blchau:3dnet
docker_pull_policy = always

executable = /radraid/blchau/3D-UNet/scripts/hippocampus/run_3-gdl/train_model.sh
arguments = /radraid/blchau/3D-UNet/scripts/hippocampus/run_3-gdl/train_config.yaml
transfer_input_files = /radraid/blchau/3D-UNet/scripts/hippocampus/run_3-gdl/train_config.yaml

should_transfer_files = YES

when_to_transfer_output = ON_EXIT

output = /radraid/blchau/3D-UNet/scripts/hippocampus/run_3-gdl/train_logs/$(cluster).$(process).out
error = /radraid/blchau/3D-UNet/scripts/hippocampus/run_3-gdl/train_logs/$(cluster).$(process).err
log = /radraid/blchau/3D-UNet/scripts/hippocampus/run_3-gdl/train_logs/$(cluster).$(process).log

request_cpus = 1
request_gpus = 1
request_memory = 12GB
request_disk = 10MB
gpus_minimum_memory = 16GB
requirements = (OpSys == "LINUX" && Arch == "X86_64")


queue
