universe=docker

docker_image = registry.cvib.ucla.edu/blchau:3dnet
docker_pull_policy = always

executable = /radraid/blchau/3D-UNet/scripts/kidney/preprocess/isotropic_preprocess.sh
arguments = $(images_path) $(labels_path) $(stats_path) $(output_path)
transfer_input_files = /radraid/blchau/3D-UNet/scripts/kidney/preprocess/isotropic_preprocess.py

should_transfer_files = YES

when_to_transfer_output = ON_EXIT

output = /radraid/blchau/3D-UNet/scripts/kidney/preprocess/logs/isotropic.$(split).$(cluster).$(process).out
error = /radraid/blchau/3D-UNet/scripts/kidney/preprocess/logs/isotropic.$(split).$(cluster).$(process).err
log = /radraid/blchau/3D-UNet/scripts/kidney/preprocess/logs/isotropic.$(split).$(cluster).$(process).log

request_cpus = 1
request_gpus = 1
request_memory = 20GB
request_disk = 200MB
gpus_minimum_memory = 10GB
requirements = (OpSys == "LINUX" && Arch == "X86_64")

queue split,images_path,labels_path,stats_path,output_path from /radraid/blchau/3D-UNet/scripts/kidney/preprocess/isotropic_args.txt