universe=docker

docker_image = registry.cvib.ucla.edu/blchau:3dnet
docker_pull_policy = always

executable = /radraid/blchau/3D-UNet/scripts/kidney/split_train_val/split_train_val.sh
arguments = /radraid/blchau/data/UCLA/preprocessed/isotropic_train /radraid/blchau/data/UCLA/preprocessed/isotropic_val
transfer_input_files = /radraid/blchau/3D-UNet/scripts/kidney/split_train_val/split_train_val.py

should_transfer_files = YES

when_to_transfer_output = ON_EXIT

output = /radraid/blchau/3D-UNet/scripts/kidney/split_train_val/logs/iso.$(cluster).$(process).out
error = /radraid/blchau/3D-UNet/scripts/kidney/split_train_val/logs/iso.$(cluster).$(process).err
log = /radraid/blchau/3D-UNet/scripts/kidney/split_train_val/logs/iso.$(cluster).$(process).log

request_cpus = 1
request_memory = 20GB
request_disk = 200MB
requirements = (OpSys == "LINUX" && Arch == "X86_64")

queue